[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 15

[studio]
enabled = true
port = 54333

[inbucket]
enabled = true
port = 54334

[analytics]
enabled = false
