import { motion } from 'framer-motion';
import { Sparkles, RefreshCw, AlertCircle, CheckCircle2 } from 'lucide-react';
import Button from '../Button';
import Card from '../Card';

interface AIContentProps {
  loading?: boolean;
  error?: string | null;
  isAIGenerated?: boolean;
  fromCache?: boolean;
  provider?: string;
  onRetry?: () => void;
  children: React.ReactNode;
  className?: string;
}

export default function AIContent({
  loading,
  error,
  isAIGenerated,
  fromCache,
  provider,
  onRetry,
  children,
  className = '',
}: AIContentProps) {
  if (loading) {
    return (
      <Card className={`p-6 ${className}`}>
        <div className="flex items-center justify-center space-x-3">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
          >
            <Sparkles className="w-6 h-6 text-blue-400" />
          </motion.div>
          <p className="text-slate-400">Generating AI insights...</p>
        </div>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className={`p-6 bg-red-500/10 border-red-500/30 ${className}`}>
        <div className="flex items-start space-x-3">
          <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-red-300 mb-3">{error}</p>
            {onRetry && (
              <Button onClick={onRetry} variant="secondary" size="sm">
                <RefreshCw className="w-4 h-4 mr-2" />
                Try Again
              </Button>
            )}
          </div>
        </div>
      </Card>
    );
  }

  return (
    <div className={className}>
      {isAIGenerated && (
        <motion.div
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center space-x-2 mb-3"
        >
          <Sparkles className="w-4 h-4 text-blue-400" />
          <span className="text-xs text-slate-400">
            AI-generated by {provider || 'AI'}
            {fromCache && ' (cached)'}
          </span>
          <CheckCircle2 className="w-3 h-3 text-green-400" />
        </motion.div>
      )}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.1 }}
      >
        {children}
      </motion.div>
    </div>
  );
}

interface AIButtonProps {
  onClick: () => void;
  loading?: boolean;
  disabled?: boolean;
  children: React.ReactNode;
  className?: string;
}

export function AIButton({
  onClick,
  loading,
  disabled,
  children,
  className = '',
}: AIButtonProps) {
  return (
    <Button
      onClick={onClick}
      disabled={disabled || loading}
      variant="secondary"
      size="sm"
      className={`${className}`}
    >
      {loading ? (
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
          className="mr-2"
        >
          <Sparkles className="w-4 h-4" />
        </motion.div>
      ) : (
        <Sparkles className="w-4 h-4 mr-2" />
      )}
      {loading ? 'Generating...' : children}
    </Button>
  );
}
