-- Phase 0: AI Onboarding & Orchestration Schemas Catch-Up (BB Prefixed)

-- 1. Onboarding Sessions Table
CREATE TABLE IF NOT EXISTS public.bb_onboarding_sessions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.bb_organizations(id) ON DELETE CASCADE,
    client_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    session_title text,
    raw_input jsonb DEFAULT '{}'::jsonb,
    ai_intelligence jsonb DEFAULT '{}'::jsonb,
    competitor_intelligence jsonb DEFAULT '{}'::jsonb,
    is_competitor_analysis_run boolean DEFAULT false,
    status text DEFAULT 'draft' CHECK (status IN ('draft', 'in_review', 'approved')),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.bb_onboarding_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view onboarding sessions in their organization" ON public.bb_onboarding_sessions;
CREATE POLICY "Users can view onboarding sessions in their organization" ON public.bb_onboarding_sessions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can update onboarding sessions in their organization" ON public.bb_onboarding_sessions;
CREATE POLICY "Users can update onboarding sessions in their organization" ON public.bb_onboarding_sessions
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can create onboarding sessions in their organization" ON public.bb_onboarding_sessions;
CREATE POLICY "Users can create onboarding sessions in their organization" ON public.bb_onboarding_sessions
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can delete onboarding sessions in their organization" ON public.bb_onboarding_sessions;
CREATE POLICY "Users can delete onboarding sessions in their organization" ON public.bb_onboarding_sessions
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );


-- 2. Onboarding Build Tasks (The Implementation Map generated by AI)
CREATE TABLE IF NOT EXISTS public.bb_onboarding_build_tasks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.bb_organizations(id) ON DELETE CASCADE,
    session_id uuid NOT NULL REFERENCES public.bb_onboarding_sessions(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    task_category text,
    antigravity_prompt text,
    is_platform_feature boolean DEFAULT false,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'rejected')),
    priority int DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.bb_onboarding_build_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view onboarding build tasks in their organization" ON public.bb_onboarding_build_tasks;
CREATE POLICY "Users can view onboarding build tasks in their organization" ON public.bb_onboarding_build_tasks
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_build_tasks.organization_id 
            AND user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can manage onboarding build tasks in their organization" ON public.bb_onboarding_build_tasks;
CREATE POLICY "Users can manage onboarding build tasks in their organization" ON public.bb_onboarding_build_tasks
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.bb_organization_memberships
            WHERE organization_id = bb_onboarding_build_tasks.organization_id 
            AND user_id = auth.uid()
        )
    );


-- 3. Telemetry Triggers for updated_at
DROP TRIGGER IF EXISTS set_timestamp_bb_onboarding_sessions ON public.bb_onboarding_sessions;
CREATE TRIGGER set_timestamp_bb_onboarding_sessions
BEFORE UPDATE ON public.bb_onboarding_sessions
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS set_timestamp_bb_onboarding_build_tasks ON public.bb_onboarding_build_tasks;
CREATE TRIGGER set_timestamp_bb_onboarding_build_tasks
BEFORE UPDATE ON public.bb_onboarding_build_tasks
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Force the API to immediately dump its memory and recognize the new table names
NOTIFY pgrst, 'reload schema';
