-- Phase 0: AI Onboarding & Orchestration Schemas

-- 1. Onboarding Sessions Table
CREATE TABLE IF NOT EXISTS public.onboarding_sessions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    client_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    session_title text,
    raw_input jsonb DEFAULT '{}'::jsonb,
    ai_intelligence jsonb DEFAULT '{}'::jsonb,
    competitor_intelligence jsonb DEFAULT '{}'::jsonb,
    is_competitor_analysis_run boolean DEFAULT false,
    status text DEFAULT 'draft' CHECK (status IN ('draft', 'in_review', 'approved')),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.onboarding_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view onboarding sessions in their organization" ON public.onboarding_sessions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can update onboarding sessions in their organization" ON public.onboarding_sessions
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can create onboarding sessions in their organization" ON public.onboarding_sessions
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete onboarding sessions in their organization" ON public.onboarding_sessions
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_sessions.organization_id 
            AND user_id = auth.uid()
        )
    );

-- 2. Onboarding Build Tasks (The Implementation Map generated by AI)
CREATE TABLE IF NOT EXISTS public.onboarding_build_tasks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    session_id uuid NOT NULL REFERENCES public.onboarding_sessions(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    task_category text,
    antigravity_prompt text,
    is_platform_feature boolean DEFAULT false,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'rejected')),
    priority int DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.onboarding_build_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view onboarding build tasks in their organization" ON public.onboarding_build_tasks
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_build_tasks.organization_id 
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can manage onboarding build tasks in their organization" ON public.onboarding_build_tasks
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.organization_memberships
            WHERE organization_id = onboarding_build_tasks.organization_id 
            AND user_id = auth.uid()
        )
    );

-- 3. Telemetry Triggers for updated_at
CREATE TRIGGER set_timestamp_onboarding_sessions
BEFORE UPDATE ON public.onboarding_sessions
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_timestamp_onboarding_build_tasks
BEFORE UPDATE ON public.onboarding_build_tasks
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();
